name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker image for PostgreSQL
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/postgresql/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/postgresql:latest
          build-args: |
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}

      - name: Build and push Docker image for Golang app
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/golang/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
          build-args: |
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}

  Deployment-Projects:
    needs: build-and-push-docker-images
    environment: master
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: kedaiprogrammer
          password: Sukses@2023
          script: |
            docker stop backend || true
            docker rm backend || true
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/postgresql:latest
            docker run -d --name postgres -e POSTGRES_USER=${{ secrets.DB_USER }} -e POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} -e POSTGRES_DB=${{ secrets.DB_NAME }} ${{ secrets.DOCKER_HUB_USERNAME }}/postgresql:latest
            docker run -d --name backend -p 8080:8080 -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=${{ secrets.DB_PORT }} -e DB_NAME=${{ secrets.DB_NAME }} -e DB_USER=${{ secrets.DB_USER }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} kedaiprogrammer/backend:latest