name: Docker Image CI
on:
  push:
    branches:
      - master

jobs:
  Build-And-Push-Docker-Images-CI:
    environment: master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image Backend Project
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest

  Deployment-Projects:
    needs: Build-And-Push-Docker-Images-CI
    environment: master
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: kedaiprogrammer
          password: Sukses@2023
          script: |
            docker stop backend || true
            docker rm backend || true
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
            docker run -d --name backend -p 8080:8080 -e DB_HOST=${{ secrets.VPS_HOST }} -e DB_PORT=${{ secrets.DB_PORT }} -e DB_NAME=${{ secrets.DB_NAME }} -e DB_USER=${{ secrets.DB_USER }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} kedaiprogrammer/backend:latest